// ── Mukth Design Tokens ─────────────────────────────────────────────────────
export const C = {
  // Emerald green family
  g900: '#011a12',
  g850: '#022c22',
  g800: '#064e3b',   // Primary brand
  g700: '#065f46',
  g600: '#047857',
  g500: '#059669',
  g100: '#d1fae5',
  g50: '#ecfdf5',

  // Gold / Sand
  gold: '#d4af37',   // Secondary brand
  goldD: '#b8941f',
  goldL: '#f0dc80',
  gold50: '#fffbea',

  // Neutrals
  white: '#ffffff',
  offW: '#fafaf8',   // Page background
  dark: '#0c1810',
  muted: '#4a6358',
  border: '#cde5d7',
  borderL: '#e8f4ef',

  // WhatsApp
  wa: '#25D366',
};

// ── WhatsApp number — !! REPLACE WITH YOUR NUMBER !! ─────────────────────────
export const WHATSAPP_NUMBER = '201220610310';

// ── Navigation links ─────────────────────────────────────────────────────────
export const NAV_LINKS = [
  { href: '#home', label: 'الرئيسية', labelEn: 'Home' },
  { href: '#about', label: 'من نحن', labelEn: 'About Us' },
  { href: '#curricula', label: 'المناهج', labelEn: 'Curricula' },
  { href: '#pricing', label: 'الأسعار', labelEn: 'Pricing' },
  { href: '#teachers', label: 'معلمونا', labelEn: 'Teachers' },
  { href: '#contact', label: 'تواصل معنا', labelEn: 'Contact' },
];

// ── Curricula data ────────────────────────────────────────────────────────────
export const CURRICULA = [
  {
    id: 'kids',
    icon: '🌱',
    title: 'حفظ للأطفال',
    titleEn: 'Kids Memorization',
    ageRange: '٦ – ١٤ سنة',
    ageRangeEn: '6 – 14 Years',
    color: '#e8f7f0',
    accent: '#047857',
    desc: 'منهج مرحلي خاص بالأطفال يجمع بين الحفظ واللعب التعليمي، مع تتبّع تقدم الطفل بشكل أسبوعي.',
    descEn: 'A phased curriculum for children combining memorization with educational play and weekly tracking.',
    features: ['حصص ترفيهية تفاعلية', 'تقرير أسبوعي للوالدين', 'معلمات متخصصات بالأطفال', 'تحفيز وشهادات تقدير'],
    featuresEn: ['Interactive leisure classes', 'Weekly parent reports', 'Specialized child teachers', 'Rewards and certificates'],
  },
  {
    id: 'adults',
    icon: '📖',
    title: 'حفظ للكبار',
    titleEn: 'Adult Memorization',
    ageRange: '١٥+ سنة',
    ageRangeEn: '15+ Years',
    color: '#faf6e8',
    accent: '#b8941f',
    desc: 'خطة حفظ منظمة للبالغين مع جداول دراسية مرنة تناسب المشغولين، ومراجعة دورية مستمرة.',
    descEn: 'Organized memorization plans for adults with flexible schedules and periodic reviews.',
    features: ['جداول مرنة على مدار اليوم', 'خطة حفظ شخصية', 'مراجعة منتظمة ومتابعة', 'حلقات جماعية ومحادثات'],
    featuresEn: ['Flexible daily schedules', 'Personalized plans', 'Regular review and follow-up', 'Group circles and discussions'],
  },
  {
    id: 'ijazah',
    icon: '🎓',
    title: 'إجازة القرآن',
    titleEn: 'Quran Ijazah',
    ageRange: 'حافظون للقرآن',
    ageRangeEn: 'Holy Quran Memorizers',
    color: '#eef2ff',
    accent: '#4338ca',
    desc: 'برنامج الإجازة بالسند المتصل برواية حفص عن عاصم، لمن أتمّ الحفظ ويرغب في نيل الإجازة.',
    descEn: 'Ijazah program with a connected chain of narration for those who have completed memorization.',
    features: ['سند متصل بالنبي ﷺ', 'معلمون مجازون فقط', 'اختبار ختامي رسمي', 'شهادة إجازة معتمدة'],
    featuresEn: ['Connected chain to the Prophet ﷺ', 'Certified ijazah teachers', 'Official final exam', 'Certified ijazah certificate'],
  },
  {
    id: 'tajweed',
    icon: '🎵',
    title: 'تجويد وتلاوة',
    titleEn: 'Tajweed & Recitation',
    ageRange: 'جميع المستويات',
    ageRangeEn: 'All Levels',
    color: '#fff0f0',
    accent: '#9f1239',
    desc: 'تعلّم أحكام التجويد من الصفر حتى الاتقان مع التطبيق العملي على آيات القرآن الكريم.',
    descEn: 'Learn tajweed rules from scratch to mastery with practical application on Quranic verses.',
    features: ['من الصفر للاحتراف', 'تسجيل وتقييم صوتي', 'أحكام التجويد كاملة', 'ممارسة مكثفة وتصحيح فوري'],
    featuresEn: ['From zero to master', 'Audio recording and evaluation', 'Complete tajweed rules', 'Intensive practice and instant correction'],
  },
];

// ── Pricing plans ─────────────────────────────────────────────────────────────
export const PLANS = [
  {
    id: 'trial',
    badge: null,
    title: 'حصة تجريبية',
    titleEn: 'Trial Session',
    price: 'مجاناً',
    priceEn: 'Free',
    priceNum: null,
    period: 'مرة واحدة',
    periodEn: 'One-time',
    features: [
      'حصة تجريبية واحدة',
      'نصف ساعة للحصة',
      'للأطفال والكبار',
      'طالب واحد',
    ],
    featuresEn: [
      'One trial session',
      '30 min session',
      'Kids & Adults',
      'One student',
    ],
    cta: 'ابدأ مجاناً',
    ctaEn: 'Start Free',
    highlight: false,
    color: '#059669', // Vibrant Green
  },
  {
    id: 'kids',
    badge: 'الأكثر طلباً',
    title: 'باقة الأطفال',
    titleEn: 'Kids Bundle',
    price: 'تواصل واتساب',
    priceEn: 'Via WhatsApp',
    priceNum: null,
    period: 'تواصل معنا',
    periodEn: 'Contact Us',
    features: [
      '٨ حصص (في الشهر)',
      'نصف ساعة للحصة',
      'للأطفال فقط',
      'طالب واحد',
    ],
    featuresEn: [
      '8 sessions (Monthly)',
      '30 min session',
      'Kids only',
      'One student',
    ],
    cta: 'اشترك الآن',
    ctaEn: 'Join Group',
    highlight: true,
    color: '#064e3b',
  },
  {
    id: 'adults',
    badge: null,
    title: 'باقة البالغين',
    titleEn: 'Adults Bundle',
    price: 'تواصل واتساب',
    priceEn: 'Via WhatsApp',
    priceNum: null,
    period: 'تواصل معنا',
    periodEn: 'Contact Us',
    features: [
      '٨ حصص (في الشهر)',
      'ساعة كاملة للحصة',
      'للبالغين',
      'طالبان',
    ],
    featuresEn: [
      '8 sessions (Monthly)',
      '1 hour session',
      'For adults',
      'Two students',
    ],
    cta: 'اشترك الآن',
    ctaEn: 'Join Group',
    highlight: false,
    color: '#064e3b',
  },
  {
    id: 'ijazah',
    badge: null,
    title: 'باقة الإجازة',
    titleEn: 'Ijazah Bundle',
    price: 'تواصل واتساب',
    priceEn: 'Via WhatsApp',
    priceNum: null,
    period: 'تواصل معنا',
    periodEn: 'Contact Us',
    features: [
      '١٢ حصة (في الشهر)',
      'ساعة كاملة للحصة',
      'للحافظين فقط',
      'طالب واحد',
    ],
    featuresEn: [
      '12 sessions (Monthly)',
      '1 hour session',
      'For memorizers only',
      'One student',
    ],
    cta: 'اشترك الآن',
    ctaEn: 'Join Group',
    highlight: false,
    color: '#064e3b',
  },
];

// ── Teachers data ─────────────────────────────────────────────────────────────
export const TEACHERS = [
  {
    id: 1,
    name: 'الشيخ معاذ عاشور',
    nameEn: 'Sheikh Moaz Ashour',
    country: 'مصر',
    countryEn: 'Egypt',
    initials: 'م.ع',
    color: '#064e3b',
    lang: ['عربي'],
    langEn: ['Arabic'],
    teaches: ['حفظ للأطفال', 'حفظ للكبار', 'إجازة القرآن', 'تجويد وتلاوة'],
    teachesEn: ['Kids Memorization', 'Adult Memorization', 'Quran Ijazah', 'Tajweed'],
    curricula: ['kids', 'adults', 'ijazah', 'tajweed'],
    rating: 4.9,
    students: 10,
  },
  {
    id: 2,
    name: 'الشيخ أحمد عرفة',
    nameEn: 'Sheikh Ahmed Arafa',
    country: 'مصر',
    countryEn: 'Egypt',
    initials: 'أ.ع',
    color: '#4338ca',
    lang: ['عربي'],
    langEn: ['Arabic'],
    teaches: ['حفظ للأطفال', 'حفظ للكبار', 'إجازة القرآن', 'تجويد وتلاوة'],
    teachesEn: ['Kids Memorization', 'Adult Memorization', 'Quran Ijazah', 'Tajweed'],
    curricula: ['kids', 'adults', 'ijazah', 'tajweed'],
    rating: 4.9,
    students: 8,
  },
  {
    id: 3,
    name: 'الأستاذة ملك محمد',
    nameEn: 'Ms. Malak Mohamed',
    country: 'مصر',
    countryEn: 'Egypt',
    initials: 'م.م',
    color: '#b8941f',
    lang: ['عربي'],
    langEn: ['Arabic'],
    teaches: ['حفظ للأطفال', 'حفظ للكبار', 'إجازة القرآن', 'تجويد وتلاوة'],
    teachesEn: ['Kids Memorization', 'Adult Memorization', 'Quran Ijazah', 'Tajweed'],
    curricula: ['kids', 'adults', 'ijazah', 'tajweed'],
    rating: 4.9,
    students: 7,
  },
  {
    id: 4,
    name: 'الشيخ محمود الحصري',
    nameEn: 'Sheikh Mahmoud Al-Hosary',
    country: 'مصر',
    countryEn: 'Egypt',
    initials: 'م.ح',
    color: '#047857',
    lang: ['عربي', 'إنجليزي'],
    langEn: ['Arabic', 'English'],
    teaches: ['حفظ للكبار', 'تجويد وتلاوة'],
    teachesEn: ['Adult Memorization', 'Tajweed'],
    curricula: ['adults', 'tajweed'],
    rating: 5.0,
    students: 6,
  },
  {
    id: 5,
    name: 'الأستاذة مريم إبراهيم',
    nameEn: 'Ms. Maryam Ibrahim',
    country: 'مصر',
    countryEn: 'Egypt',
    initials: 'م.إ',
    color: '#9f1239',
    lang: ['عربي'],
    langEn: ['Arabic'],
    teaches: ['حفظ للأطفال', 'تجويد وتلاوة'],
    teachesEn: ['Kids Memorization', 'Tajweed'],
    curricula: ['kids', 'tajweed'],
    rating: 4.8,
    students: 5,
  },
  {
    id: 6,
    name: 'الشيخ طارق عبد القادر',
    nameEn: 'Sheikh Tarek Abdelkader',
    country: 'مصر',
    countryEn: 'Egypt',
    initials: 'ط.ع',
    color: '#0284c7',
    lang: ['عربي', 'إنجليزي'],
    langEn: ['Arabic', 'English'],
    teaches: ['إجازة القرآن', 'حفظ للكبار'],
    teachesEn: ['Quran Ijazah', 'Adult Memorization'],
    curricula: ['ijazah', 'adults'],
    rating: 4.9,
    students: 4,
  },
  {
    id: 7,
    name: 'الشيخ عبدالرحمن حسن',
    nameEn: 'Sheikh Abdulrahman Hassan',
    country: 'السعودية',
    countryEn: 'Saudi Arabia',
    initials: 'ع.ح',
    color: '#7c3aed',
    lang: ['عربي'],
    langEn: ['Arabic'],
    teaches: ['تجويد وتلاوة', 'حفظ للكبار'],
    teachesEn: ['Tajweed', 'Adult Memorization'],
    curricula: ['tajweed', 'adults'],
    rating: 4.9,
    students: 3,
  },
  {
    id: 8,
    name: 'الأستاذة فاطمة الزهراء',
    nameEn: 'Ms. Fatima Al-Zahra',
    country: 'مصر',
    countryEn: 'Egypt',
    initials: 'ف.ز',
    color: '#d97706',
    lang: ['عربي'],
    langEn: ['Arabic'],
    teaches: ['حفظ للأطفال', 'تجويد وتلاوة'],
    teachesEn: ['Kids Memorization', 'Tajweed'],
    curricula: ['kids', 'tajweed'],
    rating: 5.0,
    students: 2,
  },
];

// ── Testimonials ──────────────────────────────────────────────────────────────
export const TESTIMONIALS = [
  {
    name: 'أم عمر',
    nameEn: 'Om Omar',
    role: 'ولية أمر — القاهرة',
    roleEn: 'Parent — Cairo',
    country: 'مصر',
    countryEn: 'Egypt',
    rating: 5,
    text: 'والله ما توقعت النتيجة دي بالسرعة دي! ابني حفظ ٥ أجزاء في ٤ شهور بس. المعلم بيتعامل معاه بصبر وحكمة وابني بقى يحب حصة القرآن.',
    textEn: 'I honestly did not expect results this fast! My son memorized 5 parts in just 4 months. The teacher is patient and wise, and my son now loves his Quran sessions.',
    initials: 'أ.ع',
    color: '#064e3b',
  },
  {
    name: 'محمود السيد',
    nameEn: 'Mahmoud El-Sayed',
    role: 'طالب كبار — الإسكندرية',
    roleEn: 'Adult Student — Alexandria',
    country: 'مصر',
    countryEn: 'Egypt',
    rating: 5,
    text: 'كنت بقرأ غلط من زمان ومحدش نبّهني. من يوم ما بدأت مع مُكث، الشيخ صحّح لي كل حاجة من الأول وبقيت أقرأ صح الحمد لله.',
    textEn: 'I had been reciting incorrectly for years and nobody corrected me. Since I started with Mukth, the Sheikh fixed everything from the beginning and now I recite properly.',
    initials: 'م.س',
    color: '#b8941f',
  },
  {
    name: 'هبة الله',
    nameEn: 'Hibatullah',
    role: 'طالبة إجازة — الجيزة',
    roleEn: 'Ijazah Student — Giza',
    country: 'مصر',
    countryEn: 'Egypt',
    rating: 5,
    text: 'دايماً كانت الإجازة حلمي. دلوقتي أنا قريبة جداً منها بفضل الشيخ ومتابعته المستمرة. ربنا يكرمهم على مجهودهم.',
    textEn: 'Ijazah was always my dream. Now I am very close to achieving it thanks to the Sheikh and his constant follow-up. May Allah bless them for their efforts.',
    initials: 'ه.ا',
    color: '#4338ca',
  },
  {
    name: 'كريم مصطفى',
    nameEn: 'Kareem Mostafa',
    role: 'طالب تجويد — المنصورة',
    roleEn: 'Tajweed Student — Mansoura',
    country: 'مصر',
    countryEn: 'Egypt',
    rating: 5,
    text: 'بصراحة كنت خايف أبدأ لأني كبرت، بس الأستاذ شجعني من أول حصة. دلوقتي بقرأ بشكل صح ومبقاش بخاف أقرأ قدام حد.',
    textEn: 'Honestly I was afraid to start because of my age, but the teacher encouraged me from the very first session. Now I recite correctly and I am no longer afraid to read in front of others.',
    initials: 'ك.م',
    color: '#9f1239',
  },
];
